npm install @angular/animations@latest --save
npm install @angular/common@latest --save
npm install @angular/compiler@latest --save
npm install @angular/core@latest --save
npm install @angular/flex-layout@latest --save
npm install @angular/forms@latest --save
npm install @angular/http@latest --save
npm install @angular/material@latest --save
npm install @angular/platform-browser@latest --save
npm install @angular/platform-browser-dynamic@latest --save
npm install @angular/router@latest --save